In [1]:
import torch

In [10]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward()
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [11]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
out.backward(gradient=torch.tensor(2.))

x.grad

tensor([[9., 9.],
        [9., 9.]])

In [19]:
x = torch.ones(2, requires_grad=True)
y = x + 2
y.backward(torch.tensor([10., 100]))
z = y * y * 3
out = z.mean()
out.backward()

x.grad

tensor([ 19., 109.])

https://stackoverflow.com/questions/43451125/pytorch-what-are-the-gradient-arguments

In [21]:
a = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)
b = torch.tensor([3.0, 4.0, 5.0], requires_grad = True)
c = torch.tensor([6.0, 7.0, 8.0], requires_grad = True)

y=3*a + 2*b*b + torch.log(c)    
gradients = torch.ones(3)
y.backward(gradients)  
print(a.grad) # tensor([3.0000e-01, 3.0000e+00, 3.0000e-04])
print(b.grad) # tensor([1.2000e+00, 1.6000e+01, 2.0000e-03])
print(c.grad) # tensor([1.6667e-02, 1.4286e-01, 1.2500e-05])

tensor([3., 3., 3.])
tensor([12., 16., 20.])
tensor([0.1667, 0.1429, 0.1250])


In [22]:
a = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)
b = torch.tensor([3.0, 4.0, 5.0], requires_grad = True)
c = torch.tensor([6.0, 7.0, 8.0], requires_grad = True)

y=3*a + 2*b*b + torch.log(c)    
gradients = torch.tensor([0.1, 1.0, 0.0001])
y.backward(gradients)  
print(a.grad) # tensor([3.0000e-01, 3.0000e+00, 3.0000e-04])
print(b.grad) # tensor([1.2000e+00, 1.6000e+01, 2.0000e-03])
print(c.grad) # tensor([1.6667e-02, 1.4286e-01, 1.2500e-05])

tensor([3.0000e-01, 3.0000e+00, 3.0000e-04])
tensor([1.2000e+00, 1.6000e+01, 2.0000e-03])
tensor([1.6667e-02, 1.4286e-01, 1.2500e-05])


In [32]:
a = torch.tensor(1.0, requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)
c = torch.tensor(1.0, requires_grad = True)

y=3*a + 2*b*b + torch.log(c)    
gradients = torch.tensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(a.grad) # tensor(3.3003)
print(b.grad) # tensor(4.4004)
print(c.grad) # tensor(1.1001)

tensor(3.3003)
tensor(4.4004)
tensor(1.1001)


In [42]:
a = torch.tensor(1.0, requires_grad = True)
b = torch.tensor(1.0, requires_grad = True)
c = torch.tensor(1.0, requires_grad = True)

y=3*a + 2*b*b + torch.log(c)    
gradients = torch.tensor([0.1, 1.0, 0.0001, 200])
y.backward(gradients)

print(a.grad) # tensor(3.3003)
print(b.grad) # tensor(4.4004)
print(c.grad) # tensor(1.1001)

tensor(603.3003)
tensor(804.4004)
tensor(201.1001)


In [48]:
x = torch.tensor(1.0, requires_grad=True)
y = 2*x*x
gradients = torch.tensor([1.])
y.backward(gradients)
x.grad

tensor(4.)

In [47]:
x = torch.tensor(1.0, requires_grad=True)
y = 2*x*x
gradients = torch.tensor([1., 10, 100])
y.backward(gradients)
x.grad

tensor(444.)