https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

The gradient for this tensor will be accumulated into .grad attribute.

In [91]:
import torch

In [92]:
x = torch.ones(1, requires_grad=True); x

tensor([ 1.])

In [93]:
y = x**2
z = x**3

### accumulated from `y.backward()` then `z.backward()`

In [94]:
y.backward()

In [95]:
x.grad

tensor([ 2.])

In [96]:
z.backward()

In [97]:
x.grad

tensor([ 5.])

### accumulated from `z` then `y`

In [98]:
x = torch.ones(1, requires_grad=True)
y = x**2
z = x**3

In [99]:
z.backward()

In [100]:
x.grad

tensor([ 3.])

In [101]:
y.backward()

In [102]:
x.grad

tensor([ 5.])

### Set back to 0 after `y.backward()`

In [103]:
x = torch.ones(1, requires_grad=True)
y = x**2
z = x**3

In [104]:
y.backward()

In [105]:
x.grad

tensor([ 2.])

In [106]:
x.grad.zero_()

tensor([ 0.])

In [107]:
z.backward()

In [90]:
x.grad

tensor([ 3.])