In [45]:
import torch
torch.__version__

'1.0.0.dev20181018'

In [46]:
import numpy as np

In [47]:
bs = 8
nc = 5

In [48]:
input = torch.randn(bs, nc)
input = input.sigmoid()
input.shape

torch.Size([8, 5])

In [75]:
targs = torch.randint(high=nc, size=(bs,))
targs

tensor([0, 2, 1, 2, 0, 4, 2, 4])

In [76]:
k = 10
n = targs.shape[0]
assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

AssertionError: k (10) needs to be less than or equal to the number of classes (5)

In [77]:
k = 3
n = targs.shape[0]
assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

In [78]:
input_rank = input.argsort(descending=True)
input_rank

tensor([[4, 1, 2, 0, 3],
        [3, 4, 2, 1, 0],
        [1, 2, 3, 4, 0],
        [0, 3, 2, 4, 1],
        [2, 0, 4, 3, 1],
        [1, 3, 4, 0, 2],
        [2, 4, 1, 0, 3],
        [1, 3, 0, 4, 2]])

In [79]:
input_rank_topk = input.argsort(descending=True)[:, :k]
input_rank_topk

tensor([[4, 1, 2],
        [3, 4, 2],
        [1, 2, 3],
        [0, 3, 2],
        [2, 0, 4],
        [1, 3, 4],
        [2, 4, 1],
        [1, 3, 0]])

In [80]:
bs = input.shape[0]
sum(t in input_rank_topk[i] for i, t in enumerate(targs))/bs

0.75

In [97]:
def accuracy_top_k(input, targs, k):
    "Compute top `k` accuracy with `targs` when `input` is bs * n_classes."
    n = targs.shape[0]
    assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({n})"
    input_rank_topk = input.argsort(descending=True)[:, :k]
    bs = input.shape[0]
    return torch.tensor(sum(1. if (t in input_rank_topk[i]) else 0. 
                            for i, t in enumerate(targs)) / bs)

In [98]:
accuracy_top_k(input, targs, k)

tensor(0.7500)

In [99]:
from functools import partial

In [100]:
accuracy_top_3 = partial(accuracy_top_k, k=3)
accuracy_top_3(input, targs)

tensor(0.7500)

In [101]:
def accuracy_top_3(input, targs):
    return accuracy_top_k(input, targs, k=3)
accuracy_top_3(input, targs)

tensor(0.7500)

In [102]:
# fastai
def accuracy(input, targs):
    "Compute accuracy with `targs` when `input` is bs * n_classes."
    n = targs.shape[0]
    input = input.argmax(dim=1).view(n,-1)
    targs = targs.view(n,-1)
    return (input==targs).float().mean()


In [103]:
accuracy_top_k(input, targs, 1)

tensor(0.2500)

In [104]:
accuracy(input, targs)

tensor(0.2500)