In [7]:
import torch
torch.__version__

'1.0.0.dev20181018'

In [8]:
bs = 8
nc = 4

In [9]:
y_pred = torch.randn(bs, nc)
y_pred = y_pred.sigmoid()
y_pred.shape

torch.Size([8, 4])

In [10]:
y_pred

tensor([[0.5568, 0.3550, 0.1081, 0.6210],
        [0.3643, 0.2156, 0.5884, 0.3276],
        [0.5797, 0.4956, 0.8933, 0.7701],
        [0.3460, 0.5268, 0.5305, 0.4290],
        [0.5697, 0.2854, 0.2454, 0.2785],
        [0.7663, 0.1966, 0.3188, 0.3429],
        [0.2758, 0.1488, 0.6958, 0.7163],
        [0.5620, 0.6398, 0.3983, 0.4177]])

In [11]:
y_true = torch.randint(low=0, high=2, size=(bs, nc))
y_true

tensor([[0, 1, 1, 1],
        [1, 0, 1, 1],
        [1, 0, 1, 0],
        [0, 1, 1, 1],
        [1, 1, 1, 0],
        [1, 0, 0, 1],
        [0, 1, 1, 1],
        [1, 1, 0, 0]])

https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py

https://github.com/benhamner/Metrics/tree/master/Python

!pip install ml_metrics

In [ ]:
import ml_metrics

In [ ]:
actual = y_true

## old

In [178]:
y_rank = y_pred.argsort(descending=True)
y_rank

tensor([[0, 1, 3, 2],
        [0, 1, 3, 2],
        [0, 2, 3, 1],
        [0, 1, 3, 2],
        [2, 3, 0, 1],
        [0, 3, 1, 2],
        [0, 2, 1, 3],
        [2, 1, 0, 3]])

In [179]:
k = 10
nc = y_true.shape[1]
assert 0<=k<=nc , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

AssertionError: k (10) needs to be less than or equal to the number of classes (4)

In [188]:
k = 3
nc = y_true.shape[1]
assert 0<=k<=nc , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

In [181]:
y_true

tensor([[1, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [1, 1, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]])

In [182]:
y_true_totals = y_true.sum(dim=-1).float()
y_true_totals

tensor([2., 1., 2., 1., 1., 3., 1., 1.])

In [183]:
y_rank

tensor([[0, 1, 3, 2],
        [0, 1, 3, 2],
        [0, 2, 3, 1],
        [0, 1, 3, 2],
        [2, 3, 0, 1],
        [0, 3, 1, 2],
        [0, 2, 1, 3],
        [2, 1, 0, 3]])

In [184]:
y_reorder = torch.stack([y_true_i[y_rank[i]] for i,y_true_i in enumerate(y_true)])
y_reorder

tensor([[1, 0, 0, 1],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 0, 1, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0]])

In [185]:
y_reorder_topk = y_reorder[:, :k]

In [186]:
recall_at_k = y_reorder_topk.sum(dim=-1).float() / y_true_totals
recall_at_k

tensor([0.5000, 1.0000, 1.0000, 1.0000, 1.0000, 0.6667, 1.0000, 1.0000])

In [202]:
recall_at_k.mean()

tensor(0.8958)

In [198]:
precision_at_k = y_reorder_topk.sum(dim=-1).float() / k
precision_at_k, precision_at_k.mean()

tensor([0.3333, 0.3333, 0.6667, 0.3333, 0.3333, 0.6667, 0.3333, 0.3333])

In [200]:
def precision_at_k(y_pred:Tensor, y_true:Tensor, k:int, sigmoid:bool=True):
    "Compute precision at `k` when `y_pred` and `y_true` are the same size."
    nc = y_true.shape[1]
    assert 0<=k<=nc , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"    
    if sigmoid: y_pred = y_pred.sigmoid()
    y_rank = y_pred.argsort(descending=True)
    y_reorder_topk = torch.stack([y_true_i[y_rank[i]][:k] for i,y_true_i in enumerate(y_true)])
    return (y_reorder_topk.sum(dim=-1).float() / k).mean()

In [201]:
precision_at_k(y_pred, y_true, k)

tensor(0.4167)

In [205]:
def recall_at_k(y_pred:Tensor, y_true:Tensor, k:int, sigmoid:bool=True):
    "Compute recall at `k` when `y_pred` and `y_true` are the same size."
    nc = y_true.shape[1]
    assert 0<=k<=nc , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"    
    if sigmoid: y_pred = y_pred.sigmoid()
    y_rank = y_pred.argsort(descending=True)
    y_true_totals = y_true.sum(dim=-1).float()
    y_reorder_topk = torch.stack([y_true_i[y_rank[i]][:k] for i,y_true_i in enumerate(y_true)])
    return (y_reorder_topk.sum(dim=-1).float() / y_true_totals).mean()

In [213]:
recall_at_k(y_pred, y_true, k)

tensor(0.8958)

In [208]:
from functools import partial

In [216]:
recall_at_3 = partial(recall_at_k, k=3)
recall_at_3(y_pred, y_true)

tensor(0.8958)

In [217]:
def recall_at_3(y_pred, y_true):
    return recall_at_k(y_pred, y_true, k=3)
recall_at_3(y_pred, y_true)

tensor(0.8958)