In [137]:
from torch import tensor
import torch
import numpy as np

scalar in, scalar out

In [109]:
x = tensor([1.,], requires_grad=True)
y = x**2
print('y:', y)
y.backward()
print('x.grad:', x.grad)
vᵀ = np.array([[1.]])
J = np.array([[2.]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([1.], grad_fn=<PowBackward0>)
x.grad: tensor([2.])
vᵀ: [[1.]]
J:
[[2.]]
vᵀ・J:
[[2.]]


scalar in, scalar out; non-one gradient

In [135]:
x = tensor([1.,], requires_grad=True)
y = x**2
print('y:', y)
y.backward(tensor([100.]))
print('x.grad:', x.grad)
vᵀ = np.array([[100.]])
J = np.array([[2.]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([1.], grad_fn=<PowBackward0>)
x.grad: tensor([200.])
vᵀ: [[100.]]
J:
[[2.]]
vᵀ・J:
[[200.]]


scalar in, scalar out; broadcast

In [110]:
x = tensor([1.,], requires_grad=True)
y = x**2
print('y:', y)
y.backward(tensor([1.,1.]))
print('x.grad:', x.grad)
vᵀ = np.array([[1., 1.]])
J = np.array([[2.], [2.]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([1.], grad_fn=<PowBackward0>)
x.grad: tensor([4.])
vᵀ: [[1. 1.]]
J:
[[2.]
 [2.]]
vᵀ・J:
[[4.]]


vector in, vector out

In [111]:
x = tensor([1., 2.], requires_grad=True)
y = x**2
print('y:', y)
y.backward(tensor([1.,1.]))
print('x.grad:', x.grad)
vᵀ = np.array([[1., 1.]])
J = np.array([[2., 0], [0, 4]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([1., 4.], grad_fn=<PowBackward0>)
x.grad: tensor([2., 4.])
vᵀ: [[1. 1.]]
J:
[[2. 0.]
 [0. 4.]]
vᵀ・J:
[[2. 4.]]


vector in, vector out;  non-one gradient

In [136]:
x = tensor([1., 2.], requires_grad=True)
y = x**2
print('y:', y)
y.backward(tensor([1.,10.]))
print('x.grad:', x.grad)
vᵀ = np.array([[1., 10.]])
J = np.array([[2., 0], [0, 4]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([1., 4.], grad_fn=<PowBackward0>)
x.grad: tensor([ 2., 40.])
vᵀ: [[ 1. 10.]]
J:
[[2. 0.]
 [0. 4.]]
vᵀ・J:
[[ 2. 40.]]


vector in, scalar out

In [132]:
x = tensor([1., 2.], requires_grad=True)
y = sum(x)
print('y:', y)
y.backward()
print('x.grad:', x.grad)
vᵀ = np.array([[1.,]])
J = np.array([[1., 1.]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor(3., grad_fn=<AddBackward0>)
x.grad: tensor([1., 1.])
vᵀ: [[1.]]
J:
[[1. 1.]]
vᵀ・J:
[[1. 1.]]


vector in, scalar out; broadcast

In [134]:
x = tensor([1., 2.], requires_grad=True)
y = sum(x)
print('y:', y)
y.backward(tensor([1., 100, 1000]))
print('x.grad:', x.grad)
vᵀ = np.array([[1.,100, 1000]])
J = np.array([[1., 1.], [1., 1.], [1., 1.]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor(3., grad_fn=<AddBackward0>)
x.grad: tensor([1101., 1101.])
vᵀ: [[   1.  100. 1000.]]
J:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
vᵀ・J:
[[1101. 1101.]]


scalar in, vector out

In [143]:
x = tensor([1.,], requires_grad=True)
y = torch.cat((3*x, x**2))
print('y:', y)
y.backward(tensor([1., 1.]))
print('x.grad:', x.grad)
vᵀ = np.array([[1.,1.]])
J = np.array([[3.,],[2]])
print('vᵀ:', vᵀ)
print('J:')
print(J)
print('vᵀ・J:')
print(vᵀ@J)

y: tensor([3., 1.], grad_fn=<CatBackward>)
x.grad: tensor([5.])
vᵀ: [[1. 1.]]
J:
[[3.]
 [2.]]
vᵀ・J:
[[5.]]


# old

In [ ]:
v

In [39]:
x = tensor([1.], requires_grad=True)
y = x**2
display(y)
v = tensor([[1., 1.]])
y.backward(v)
display(x.grad)
vT = v.t()
J = tensor([2., 2.])
matmul(vT,J)

tensor([1.], grad_fn=<PowBackward0>)

tensor([4.])

RuntimeError: size mismatch, [2 x 1], [2] at /Users/administrator/nightlies/2018_11_30/wheel_build_dirs/conda_3.7/conda/conda-bld/pytorch-nightly_1543580748233/work/aten/src/TH/generic/THTensorMath.cpp:815

In [27]:
x = tensor([1.], requires_grad=True)
y = x**2
display(y)
y.backward()
display(x.grad)
vT = tensor([1.])
J = tensor([2.])
matmul(vT,J)

tensor([1.], grad_fn=<PowBackward0>)

tensor([2.])

tensor(2.)

In [28]:
x = tensor([1.], requires_grad=True)
y = x**2
display(y)
y.backward(gradient=tensor([2.]))
display(x.grad)
vT = tensor([2.]])
J = tensor([[2.]])
mm(vT,J)

tensor([1.], grad_fn=<PowBackward0>)

tensor([4.])

tensor([[2.]])

In [12]:
x = tensor(1., requires_grad=True)
y = x**2
display(y)
y.backward(gradient=tensor(2.))
display(x.grad)

tensor(1., grad_fn=<PowBackward0>)

tensor(4.)

In [13]:
x = tensor(1., requires_grad=True)
y = x**2
display(y)
y.backward(gradient=tensor([1.,1.]))
display(x.grad)

tensor(1., grad_fn=<PowBackward0>)

tensor(4.)

In [14]:
x = tensor(1., requires_grad=True)
y = x**2
display(y)
y.backward(gradient=tensor([1.,10.]))
display(x.grad)

tensor(1., grad_fn=<PowBackward0>)

tensor(22.)

In [15]:
x = tensor([1.], requires_grad=True)
y = x**2
display(y)
y.backward(gradient=tensor([1.,10.]))
display(x.grad)

tensor([1.], grad_fn=<PowBackward0>)

tensor([22.])

In [17]:
x = tensor([1., 1.], requires_grad=True)
y = x**2
display(y)
y.backward()
display(x.grad)

tensor([1., 1.], grad_fn=<PowBackward0>)

RuntimeError: grad can be implicitly created only for scalar outputs