In [6]:
!echo $CONDA_PREFIX

/Users/yang.zhang/anaconda3/envs/fastai-cpu


In [982]:
import numpy as np

from torch.autograd import Variable
import torch
import torch.nn.functional as F
import torch.nn as nn
torch.__version__

'0.3.1.post2'

## L1Loss

In [350]:
x = Variable(torch.randn(2, 3), requires_grad=True)
y = Variable(torch.randn(2, 3))

In [351]:
x.requires_grad, y.requires_grad

(True, False)

In [352]:
x

Variable containing:
 0.7542  1.4145  2.9330
 0.4976  0.5601  1.6179
[torch.FloatTensor of size 2x3]

In [353]:
y

Variable containing:
-1.1977 -1.0040 -0.6565
 0.2359  0.8494  2.1820
[torch.FloatTensor of size 2x3]

In [354]:
loss = nn.L1Loss()

lss = loss(x, y)
lss

Variable containing:
 1.5125
[torch.FloatTensor of size 1]

In [355]:
F.l1_loss(x, y)

Variable containing:
 1.5125
[torch.FloatTensor of size 1]

In [356]:
lss.backward()

x.grad

Variable containing:
 0.1667  0.1667  0.1667
 0.1667 -0.1667 -0.1667
[torch.FloatTensor of size 2x3]

In [357]:
y.grad is None

True

In [358]:
loss = nn.L1Loss(size_average=False)

lss = loss(x, y)
lss

Variable containing:
 9.0751
[torch.FloatTensor of size 1]

In [359]:
# if reduce is False, size_average is ignored
loss = nn.L1Loss(size_average=False, reduce=False)

lss = loss(x, y)
lss

Variable containing:
 1.9519  2.4185  3.5895
 0.2617  0.2894  0.5641
[torch.FloatTensor of size 2x3]

In [360]:
loss = nn.L1Loss(reduce=False)

lss = loss(x, y)
lss

Variable containing:
 1.9519  2.4185  3.5895
 0.2617  0.2894  0.5641
[torch.FloatTensor of size 2x3]

In [361]:
lss.sum()

Variable containing:
 9.0751
[torch.FloatTensor of size 1]

In [362]:
lss.mean()

Variable containing:
 1.5125
[torch.FloatTensor of size 1]

In [363]:
lss.mean(dim=1)

Variable containing:
 2.6533
 0.3717
[torch.FloatTensor of size 2]

In [364]:
lss.backward(torch.ones(2, 3))

x.grad

Variable containing:
 1.1667  1.1667  1.1667
 1.1667 -1.1667 -1.1667
[torch.FloatTensor of size 2x3]

In [365]:
F.l1_loss(x, y, size_average=False, reduce=False)

Variable containing:
 1.9519  2.4185  3.5895
 0.2617  0.2894  0.5641
[torch.FloatTensor of size 2x3]

In [366]:
F.l1_loss(x, y,  reduce=False)

Variable containing:
 1.9519  2.4185  3.5895
 0.2617  0.2894  0.5641
[torch.FloatTensor of size 2x3]

In [367]:
abs(x.data.numpy() - y.data.numpy())

array([[1.9518584 , 2.4185286 , 3.5895407 ],
       [0.26172477, 0.28938198, 0.56411517]], dtype=float32)

### custom

In [368]:
class MyL1Loss(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x, y):
        return (x - y).abs().mean()

In [369]:
x = Variable(torch.randn(2, 3), requires_grad=True)
y = Variable(torch.randn(2, 3))

In [370]:
mylss = MyL1Loss()(x, y)
mylss.backward()
mylss

Variable containing:
 1.2744
[torch.FloatTensor of size 1]

In [371]:
lss = nn.L1Loss()(x, y)
lss

Variable containing:
 1.2744
[torch.FloatTensor of size 1]

## SmoothL1Loss

In [915]:
x = Variable(torch.randn(2, 3), requires_grad=True)
y = Variable(torch.randn(2, 3))

In [916]:
nn.SmoothL1Loss()(x, y)

Variable containing:
 0.8527
[torch.FloatTensor of size 1]

In [917]:
nn.SmoothL1Loss(reduce=False)(x, y)

Variable containing:
 0.4337  0.2273  0.8062
 1.5683  2.0171  0.0636
[torch.FloatTensor of size 2x3]

In [918]:
x = x.data.numpy() 
y = y.data.numpy()

In [919]:
def smoothl1loss(x, y):
    if abs(x-y)<1: return 1/2*(x-y)**2
    else: return abs(x-y)-1/2

In [920]:
lst = []
for i in range(len(x)):
    lsti=[]
    for j in range(len(x[i])):
        lsti.append(smoothl1loss(x[i][j], y[i][j]))
    lst.append(lsti)
lst, np.mean(lst)

([[0.433673763595948, 0.22726064287826375, 0.8062185049057007],
  [1.5682995319366455, 2.0171167850494385, 0.06357977724910491]],
 0.8526915009358502)

## MSELoss

In [372]:
x = Variable(torch.randn(2, 3), requires_grad=True)
y = Variable(torch.randn(2, 3))

In [373]:
x.requires_grad, y.requires_grad

(True, False)

In [374]:
x

Variable containing:
-1.0188  0.2023  0.2464
 0.6104 -0.5254  1.8013
[torch.FloatTensor of size 2x3]

In [375]:
y

Variable containing:
 0.7453  1.4843  0.5891
-0.5032  0.6882 -0.5134
[torch.FloatTensor of size 2x3]

In [376]:
loss = nn.MSELoss()

lss = loss(x, y)
lss

Variable containing:
 2.1573
[torch.FloatTensor of size 1]

In [377]:
F.mse_loss(x, y)

Variable containing:
 2.1573
[torch.FloatTensor of size 1]

In [378]:
lss.backward()

x.grad

Variable containing:
-0.5880 -0.4274 -0.1142
 0.3712 -0.4045  0.7716
[torch.FloatTensor of size 2x3]

In [379]:
y.grad is None

True

In [380]:
loss = nn.MSELoss(size_average=False)

lss = loss(x, y)
lss

Variable containing:
 12.9437
[torch.FloatTensor of size 1]

In [381]:
# if reduce is False, size_average is ignored
loss = nn.MSELoss(size_average=True, reduce=False)

lss = loss(x, y)
lss

Variable containing:
 3.1117  1.6437  0.1175
 1.2401  1.4729  5.3579
[torch.FloatTensor of size 2x3]

In [382]:
loss = nn.MSELoss(reduce=False)

lss = loss(x, y)
lss

Variable containing:
 3.1117  1.6437  0.1175
 1.2401  1.4729  5.3579
[torch.FloatTensor of size 2x3]

In [383]:
lss.sum()

Variable containing:
 12.9437
[torch.FloatTensor of size 1]

In [384]:
lss.mean()

Variable containing:
 2.1573
[torch.FloatTensor of size 1]

In [385]:
lss.mean(dim=1)

Variable containing:
 1.6243
 2.6903
[torch.FloatTensor of size 2]

In [386]:
lss.backward(torch.ones(2, 3))

x.grad

Variable containing:
-4.1160 -2.9915 -0.7997
 2.5984 -2.8318  5.4010
[torch.FloatTensor of size 2x3]

In [389]:
F.mse_loss(x, y, reduce=False)

Variable containing:
 3.1117  1.6437  0.1175
 1.2401  1.4729  5.3579
[torch.FloatTensor of size 2x3]

In [390]:
(x.data.numpy() - y.data.numpy())**2

array([[3.1117244 , 1.6436725 , 0.11746262],
       [1.2400689 , 1.4728769 , 5.3578777 ]], dtype=float32)

## CrossEntropyLoss

In [391]:
x = Variable(torch.randn(2, 4))
y = Variable(torch.LongTensor(2).random_(4))
x, y

(Variable containing:
  1.0245  0.8270  1.2741  1.6792
 -1.2916 -1.7446 -0.2974 -0.2256
 [torch.FloatTensor of size 2x4], Variable containing:
  0
  0
 [torch.LongTensor of size 2])

In [392]:
loss = nn.CrossEntropyLoss()
lss = loss(x, y)
lss

Variable containing:
 1.7975
[torch.FloatTensor of size 1]

In [393]:
F.cross_entropy(x, y)

Variable containing:
 1.7975
[torch.FloatTensor of size 1]

In [394]:
F.cross_entropy(x, y, reduce=False)

Variable containing:
 1.6152
 1.9799
[torch.FloatTensor of size 2]

In [395]:
F.cross_entropy(x, y, reduce=False).mean()

Variable containing:
 1.7975
[torch.FloatTensor of size 1]

In [396]:
x = x.data.numpy()
y = y.data.numpy()

In [397]:
for i in range(len(x)):
    print(np.exp(x[i][y[i]])/np.exp(x[i]).sum())

0.19884911
0.13808674


In [398]:
for i in range(len(x)):
    print(-np.log(np.exp(x[i][y[i]])/np.exp(x[i]).sum()))

1.615209
1.9798733


## LogSoftmax

In [399]:
x = Variable(torch.randn(2, 4))
y = nn.LogSoftmax(dim=1)(x)
x, y

(Variable containing:
 -1.1917 -0.0173  0.3792 -2.1996
 -2.6137  0.8747  0.6576  0.2841
 [torch.FloatTensor of size 2x4], Variable containing:
 -2.2420 -1.0676 -0.6711 -3.2499
 -4.3594 -0.8711 -1.0881 -1.4617
 [torch.FloatTensor of size 2x4])

In [400]:
x = x.data.numpy()

for i in range(len(x)):
    print(np.log( np.exp(x[i]) / np.exp(x[i]).sum()) )

[-2.2419775 -1.0675703 -0.6711322 -3.2498698]
[-4.359395   -0.87106586 -1.0880961  -1.4616584 ]


## NLLLoss

negative log likelihood

In [401]:
x0 = Variable(torch.randn(2, 4), requires_grad=True)
x = nn.LogSoftmax(dim=1)(x0)
x0, x

(Variable containing:
  1.9038 -1.1510  0.3855 -1.1231
  0.0218  0.8157 -1.5796 -1.0934
 [torch.FloatTensor of size 2x4], Variable containing:
 -0.2736 -3.3284 -1.7919 -3.3005
 -1.3195 -0.5256 -2.9209 -2.4347
 [torch.FloatTensor of size 2x4])

In [402]:
y = Variable(torch.LongTensor(2).random_(4))
y

Variable containing:
 3
 3
[torch.LongTensor of size 2]

In [403]:
loss = nn.NLLLoss()
lss = loss(x, y)
lss

Variable containing:
 2.8676
[torch.FloatTensor of size 1]

In [404]:
loss = nn.NLLLoss(reduce=False)
lss = loss(x, y)
lss

Variable containing:
 3.3005
 2.4347
[torch.FloatTensor of size 2]

In [405]:
F.nll_loss(x, y, reduce=False)

Variable containing:
 3.3005
 2.4347
[torch.FloatTensor of size 2]

In [406]:
F.nll_loss(x, y, reduce=True), F.nll_loss(x, y, reduce=False).mean()

(Variable containing:
  2.8676
 [torch.FloatTensor of size 1], Variable containing:
  2.8676
 [torch.FloatTensor of size 1])

In [407]:
x = x.data.numpy()
y = y.data.numpy()
for i in range(len(x)):
    print(-x[i][y[i]])

3.3005364
2.4346604


## PoissonNLLLoss

In [408]:
log_input = Variable(torch.randn(5, 2), requires_grad=True)
target = Variable(torch.randn(5, 2))
log_input, target

(Variable containing:
  2.0718  1.0890
  0.4089  1.8608
  0.3788 -1.2807
  0.1001 -0.1797
  0.6171 -0.8649
 [torch.FloatTensor of size 5x2], Variable containing:
  2.7363 -0.6778
 -0.8334 -1.8356
 -1.1483 -0.2895
 -0.7879  0.5216
 -0.4458  0.5525
 [torch.FloatTensor of size 5x2])

In [409]:
loss = nn.PoissonNLLLoss()
output = loss(log_input, target)
output

Variable containing:
 2.4614
[torch.FloatTensor of size 1]

In [410]:
loss = nn.PoissonNLLLoss(size_average=False)
output = loss(log_input, target)
output

Variable containing:
 24.6136
[torch.FloatTensor of size 1]

In [411]:
loss = nn.PoissonNLLLoss(reduce=False)
output = loss(log_input, target)
output, output.sum(), output.mean()

(Variable containing:
  2.2700  3.7094
  1.8460  9.8445
  1.8955 -0.0930
  1.1842  0.9292
  2.1287  0.8990
 [torch.FloatTensor of size 5x2], Variable containing:
  24.6136
 [torch.FloatTensor of size 1], Variable containing:
  2.4614
 [torch.FloatTensor of size 1])

## NLLLoss2d

In [412]:
# input is of size N x C x height x width
input = Variable(torch.randn(3, 16, 10, 10))
# each element in target has to have 0 <= value < C
target = Variable(torch.LongTensor(3, 8, 8).random_(0, 4))
input, target

(Variable containing:
 (0 ,0 ,.,.) = 
  -1.4805  0.1829  1.4143  ...   0.2693 -0.9812 -0.7538
   0.6935  0.1245  0.2418  ...   0.4276  0.6250  0.8744
   0.8419 -1.0050 -2.3323  ...  -0.1464 -1.0452  0.7208
            ...             ⋱             ...          
   1.6107 -0.7012  0.5927  ...  -1.1020 -1.0032 -0.8127
  -0.7220  0.6516 -0.6696  ...  -0.1151 -0.1100 -0.5977
   1.5033 -0.2086 -0.0529  ...  -0.8170  0.7933 -1.2924
 
 (0 ,1 ,.,.) = 
  -0.9359  0.9143  1.0664  ...   0.4395  0.7890  0.2211
   0.2445  0.4530  0.1255  ...  -0.2919 -0.8629  0.6840
  -0.4183 -0.5049  1.0907  ...   1.5985  1.7811  0.1448
            ...             ⋱             ...          
   0.1514 -0.2225  1.0818  ...   2.9254  0.0690  0.7735
  -0.1044 -0.7817  0.5361  ...  -0.9152  0.1318  0.7803
  -1.9023  0.2213  1.3726  ...   1.4722 -0.4702 -1.9503
 
 (0 ,2 ,.,.) = 
   0.4204 -0.2001  0.0018  ...   0.6741  0.5988  0.7767
   1.8723 -0.3207 -1.6236  ...  -0.8549 -0.5497 -0.2016
   2.2799 -1.6071  0.5498  ...

In [413]:
m = nn.Conv2d(16, 32, (3, 3)).float()
m(input)

Variable containing:
(0 ,0 ,.,.) = 
 -0.0914 -0.3414 -0.5887  ...   0.0901 -0.4334  0.1536
  0.3325  0.3335 -0.2382  ...   0.1678  0.1553  0.3347
 -1.4213 -0.5045  0.3120  ...  -0.6401  0.5019 -0.6772
           ...             ⋱             ...          
  0.1373 -0.0388 -0.1407  ...   0.2154 -0.3195 -0.5756
 -1.3767  0.0899 -0.7323  ...  -0.3288  0.4410 -0.8754
  0.8808 -0.1628 -0.6851  ...   0.5875  0.0808 -1.0219

(0 ,1 ,.,.) = 
  1.0110  0.6205 -0.1065  ...   0.4678 -0.6539 -0.2291
  0.5658  0.3720  0.6709  ...   0.3127 -1.1345  0.4468
  0.1602  0.5106 -0.0117  ...  -0.4563 -0.4087  0.6784
           ...             ⋱             ...          
  0.6720 -0.4646 -0.9028  ...  -0.7556  0.5702 -0.3176
 -0.3631 -0.4161 -0.3207  ...   0.1507  0.6462  0.5372
  0.1930 -0.1476  0.2946  ...   0.3118 -0.4873  0.7928

(0 ,2 ,.,.) = 
 -0.3416 -0.0683  0.4018  ...  -0.1521 -0.7236 -0.7863
  0.3424 -0.1474 -0.9320  ...   0.7171  0.3830 -0.8341
 -0.2295 -0.2255 -0.4940  ...   0.2875 -0.2093  0.31

In [414]:
loss = nn.NLLLoss2d()
output = loss(m(input), target)
output

Variable containing:
1.00000e-02 *
  7.0827
[torch.FloatTensor of size 1]

In [415]:
loss = nn.NLLLoss2d(reduce=False)
output = loss(m(input), target)
output

Variable containing:
(0 ,.,.) = 
  1.2352  0.3414  0.5887  1.2551 -0.1083  0.8254  0.6539  0.4949
 -0.1060  0.3918  0.9320 -0.6697 -0.6308 -0.7171 -0.3830  0.0484
  0.0691  0.2255 -0.3308  0.9047 -1.2582  0.4563 -0.5019 -0.6784
 -0.6251 -0.4932  0.0001  0.2578 -0.7864  0.3773  0.0654  0.7104
 -0.8741 -0.2491  0.3755  0.4965  0.7590 -0.2958  0.3633  0.6539
 -0.6254  0.0388  0.9028  0.2724  1.1647  0.9333 -0.5702 -0.3482
  1.3767  0.4161  0.3207 -0.0584  0.9915  0.3288  0.5114  0.8754
  0.9526  0.3574 -0.2946 -0.5176  0.2095  1.1140 -0.0808 -0.7928

(1 ,.,.) = 
  0.0098  0.7049  0.2768 -0.3276  0.9695  0.1490  0.1431  1.0447
 -0.7122 -0.7132  0.1235  0.5176 -0.3217 -0.0980  0.1967 -0.7140
  0.2363 -0.6067 -1.8679  0.1546 -1.0182 -0.9606  0.0163  0.5357
 -0.5395  0.6787 -0.7396 -0.0542  0.0519  1.1760  0.6621  0.3212
  0.6533 -0.3661 -0.3049  0.0005 -0.7431  0.9055 -0.3869 -0.1436
  1.2762  0.4494  0.3437 -0.7135 -0.2977 -0.5268  0.3303 -0.9602
  0.0089  0.2960 -0.2752  0.1159  0.2105  0.

## KLDivLoss

In [715]:
x = Variable(torch.rand(2, 3))
y = Variable(torch.rand(2, 3))
x, y

(Variable containing:
  0.8813  0.8005  0.1786
  0.9045  0.4765  0.5855
 [torch.FloatTensor of size 2x3], Variable containing:
  0.8777  0.5932  0.7239
  0.5772  0.9740  0.6644
 [torch.FloatTensor of size 2x3])

In [716]:
loss=nn.KLDivLoss()
lss=loss(x, y)
lss

Variable containing:
-0.6709
[torch.FloatTensor of size 1]

In [717]:
loss=nn.KLDivLoss(size_average=False)
lss=loss(x, y)
lss

Variable containing:
-4.0256
[torch.FloatTensor of size 1]

In [718]:
loss=nn.KLDivLoss(reduce=False)
lss=loss(x, y)
lss

Variable containing:
-0.8881 -0.7846 -0.3632
-0.8393 -0.4898 -0.6606
[torch.FloatTensor of size 2x3]

In [719]:
lss.mean(), lss.sum()

(Variable containing:
 -0.6709
 [torch.FloatTensor of size 1], Variable containing:
 -4.0256
 [torch.FloatTensor of size 1])

In [720]:
x = x.data.numpy()
y = y.data.numpy()

In [723]:
lst = []
for i in range(len(x)):
    lsti = []
    for j in range(len(x[i])):
        # xi is already log 
        lsti.append(y[i][j] * (np.log(y[i][j]) - x[i][j]))
    lst.append(lsti)
lst, np.mean(lst)

([[-0.8880524, -0.7846184, -0.3632179],
  [-0.83927226, -0.48979017, -0.66064775]],
 -0.6709332)

## Sigmoid

In [438]:
x = Variable(torch.randn(2, 4))
y = nn.Sigmoid()(x)
x, y

(Variable containing:
  0.6375  0.9128 -2.0614  0.0657
 -0.2632 -0.8791  1.3737  1.6586
 [torch.FloatTensor of size 2x4], Variable containing:
  0.6542  0.7136  0.1129  0.5164
  0.4346  0.2934  0.7980  0.8401
 [torch.FloatTensor of size 2x4])

In [ ]:
x = x.data.numpy()

In [442]:
1 / (1 + np.exp(-x))

array([[0.6541974 , 0.71358067, 0.11290552, 0.5164305 ],
       [0.4345839 , 0.29336274, 0.7979727 , 0.84005225]], dtype=float32)

## BCELoss

### single label

In [484]:
x0 = Variable(torch.randn(3))
x = nn.Sigmoid()(x0)

y = Variable(torch.FloatTensor(3).random_(2))
x, y

(Variable containing:
  0.2975
  0.3784
  0.3778
 [torch.FloatTensor of size 3], Variable containing:
  1
  0
  0
 [torch.FloatTensor of size 3])

In [485]:
loss = nn.BCELoss()
lss = loss(x, y)
lss, lss*len(x)

(Variable containing:
  0.7208
 [torch.FloatTensor of size 1], Variable containing:
  2.1624
 [torch.FloatTensor of size 1])

In [486]:
loss = nn.BCELoss(size_average=False)
lss = loss(x, y)
lss

Variable containing:
 2.1624
[torch.FloatTensor of size 1]

In [487]:
x = x.data.numpy()
y = y.data.numpy()

lst = []
for i in range(len(x)):
    lst.append(-np.log(x[i]) if y[i]==1 else -np.log(1-x[i]))
lst, np.mean(lst), np.sum(lst)

([1.212439, 0.47547434639676955, 0.47444362242937016],
 0.720785636609344,
 2.162356909828032)

In [488]:
lst = []
for i in range(len(x)):
    lst.append(-np.log(x[i]) if y[i]==1 else -np.log(1-x[i]))
lst, np.mean(lst), np.sum(lst)

([1.212439, 0.47547434639676955, 0.47444362242937016],
 0.720785636609344,
 2.162356909828032)

In [489]:
lst = []
for i in range(len(x)):
    lst.append(-np.log(x[i])*y[i] + -np.log(1-x[i])*(1-y[i]))
lst, np.mean(lst), np.sum(lst)

([1.212438941001892, 0.47547434639676955, 0.47444362242937016],
 0.720785636609344,
 2.162356909828032)

### multilabel

In [492]:
x0 = Variable(torch.randn(3, 2))
x = nn.Sigmoid()(x0)

y = Variable(torch.FloatTensor(3, 2).random_(2))
x, y

(Variable containing:
  0.5547  0.7939
  0.3316  0.4920
  0.5952  0.5797
 [torch.FloatTensor of size 3x2], Variable containing:
  0  0
  1  1
  0  0
 [torch.FloatTensor of size 3x2])

In [493]:
loss = nn.BCELoss()
lss = loss(x, y)
lss

Variable containing:
 0.9954
[torch.FloatTensor of size 1]

In [ ]:
x = x.data.numpy()
y = y.data.numpy()

In [503]:
lst = []
for i in range(len(x)):
    lsti = []
    for j in range(len(x[i])):
        lsti.append(-np.log(x[i][j]) if y[i][j]==1 else -np.log(1-x[i][j]))
    lst.append(lsti)
np.array(lst), np.mean(lst), np.sum(lst)

(array([[0.80890766, 1.57933168],
        [1.10379136, 0.70931298],
        [0.9044003 , 0.86669647]]), 0.9954067403303868, 5.972440441982321)

In [496]:
lst = []
for i in range(len(x)):
    lst.append(-np.log(x[i])*y[i] + -np.log(1-x[i])*(1-y[i]))
lst, np.mean(lst), np.sum(lst)

([array([0.8089076, 1.5793316], dtype=float32),
  array([1.1037914, 0.709313 ], dtype=float32),
  array([0.9044003, 0.8666965], dtype=float32)],
 0.9954067,
 5.9724402)

## BCEWithLogitsLoss

### single label

In [505]:
x = Variable(torch.randn(3))
xs = nn.Sigmoid()(x)

y = Variable(torch.FloatTensor(3).random_(2))
x, y

(Variable containing:
  1.6919
  0.3915
 -0.6003
 [torch.FloatTensor of size 3], Variable containing:
  0
  1
  1
 [torch.FloatTensor of size 3])

In [506]:
loss = nn.BCELoss()
lss = loss(xs, y)
lss

Variable containing:
 1.1383
[torch.FloatTensor of size 1]

In [507]:
loss = nn.BCEWithLogitsLoss()
lss = loss(x, y)
lss

Variable containing:
 1.1383
[torch.FloatTensor of size 1]

### multilabel

In [510]:
x = Variable(torch.randn(3, 2))
xs = nn.Sigmoid()(x)

y = Variable(torch.FloatTensor(3, 2).random_(2))
x, y

(Variable containing:
 -0.8044  0.8187
  0.8414 -1.7095
 -1.4606 -1.7738
 [torch.FloatTensor of size 3x2], Variable containing:
  0  1
  1  1
  1  1
 [torch.FloatTensor of size 3x2])

In [512]:
loss = nn.BCELoss()
lss = loss(xs, y)
lss

Variable containing:
 1.0949
[torch.FloatTensor of size 1]

In [513]:
loss = nn.BCEWithLogitsLoss()
lss = loss(x, y)
lss

Variable containing:
 1.0949
[torch.FloatTensor of size 1]

## MultiLabelSoftMarginLoss

## MarginRankingLoss

In [932]:
x1 = Variable(torch.randn(3))
x2 = Variable(torch.randn(3))
y = Variable(torch.FloatTensor(np.random.choice([1, -1], 3)))

x1, x2, y

(Variable containing:
  1.1673
  1.2137
 -1.3999
 [torch.FloatTensor of size 3], Variable containing:
 -1.4045
 -1.6424
  0.3971
 [torch.FloatTensor of size 3], Variable containing:
 -1
  1
  1
 [torch.FloatTensor of size 3])

In [933]:
loss = nn.MarginRankingLoss(margin=0.1)
loss(x1, x2, y)

Variable containing:
 1.5229
[torch.FloatTensor of size 1]

In [934]:
x1 = x1.data.numpy()
x2 = x2.data.numpy()
y = y.data.numpy()
margin=0.1

In [935]:
lst = []
for i in range(len(x1)):
    lst.append(max(0, -y[i]*(x1[i]-x2[i]) + margin))

lst, np.mean(lst)

([2.6717973709106446, 0, 1.896928644180298], 1.5229086716969809)

## CosineEmbeddingLoss

In [998]:
x1 = Variable(torch.randn(2, 3))
x2 = Variable(torch.randn(2, 3))
y = Variable(torch.FloatTensor(np.random.choice([1, -1], 2)))

x1, x2, y

(Variable containing:
 -0.6578  1.1298 -0.8769
 -0.2806  1.7066  2.8308
 [torch.FloatTensor of size 2x3], Variable containing:
 -0.5813  1.3849 -1.2074
 -1.1931 -1.3090  0.8771
 [torch.FloatTensor of size 2x3], Variable containing:
  1
  1
 [torch.FloatTensor of size 2])

In [999]:
nn.CosineEmbeddingLoss(margin=0.1)(x1, x2, y)

Variable containing:
 0.4601
[torch.FloatTensor of size 1]

In [1000]:
x1 = x1.data.numpy()
x2 = x2.data.numpy()
y = y.data.numpy()
margin=0.1

In [1005]:
from scipy.spatial.distance import cosine

def cos(x, y): return 1-cosine(x, y)

In [1006]:
lst = []
for k in range(len(x1)):
    if y[k] == 1: lst.append(1-cos(x1[k], x2[k]))
    elif y[k] == -1: lst.append(max(0, cos(x1[k], x2[k])-margin))
lst, np.mean(lst)

([0.009168565273284912, 0.9109426885843277], 0.4600556269288063)

## HingeEmbeddingLoss

In [925]:
x = Variable(torch.randn(2, 3))
y = Variable(torch.FloatTensor(np.random.choice([-1, 1], (2, 3))))

x, y

(Variable containing:
  1.1572 -0.6421  0.6631
  0.3357 -0.2172  0.2704
 [torch.FloatTensor of size 2x3], Variable containing:
 -1  1 -1
  1 -1 -1
 [torch.FloatTensor of size 2x3])

In [926]:
loss = nn.HingeEmbeddingLoss(margin=1)

loss(x, y)

Variable containing:
 0.3295
[torch.FloatTensor of size 1]

In [927]:
loss = nn.HingeEmbeddingLoss(margin=1)

loss(x, y)

Variable containing:
 0.3295
[torch.FloatTensor of size 1]

In [928]:
x = x.data.numpy()
y = y.data.numpy()
margin=1

In [929]:
lst=[]

for i in range(len(x)):
    lsti = []
    for j in range(len(x[i])):
        if y[i][j]==1:
            lsti.append(x[i][j])
        else:
            lsti.append(max(0, margin-x[i][j]))
    lst.append(lsti)
lst, np.mean(lst)

([[0, -0.6421209, 0.33689743280410767],
  [0.33567223, 1.2171948850154877, 0.7295853793621063]],
 0.32953817149003345)

## SoftMarginLoss

In [943]:
x = Variable(torch.randn(2, 4))
y = Variable(torch.FloatTensor(np.random.choice([-1, 1], (2, 4))))
x, y

(Variable containing:
 -0.5403  0.6454 -0.5838  1.8870
 -0.4422  0.7832  0.8684  0.4095
 [torch.FloatTensor of size 2x4], Variable containing:
 -1 -1  1  1
 -1  1  1 -1
 [torch.FloatTensor of size 2x4])

In [944]:
nn.SoftMarginLoss()(x, y)

Variable containing:
 0.6045
[torch.FloatTensor of size 1]

In [946]:
x = x.data.numpy()
y = y.data.numpy()

In [953]:
lst = []
for k in range(len(x)):
    sm = 0
    for i in range(len(x[k])):
        sm += np.log(1 + np.exp(-y[k][i]*x[k][i]))
    lst.append(sm/len(x[k]))

lst, np.mean(lst)

([0.6735555645482193, 0.5354263938608341], 0.6044909792045268)

## MultiLabelSoftMarginLoss

In [960]:
x = Variable(torch.randn(2, 4))
y = Variable(torch.FloatTensor(2, 4).random_(2))
x, y

(Variable containing:
  0.9519 -1.7461  1.3948 -0.6149
 -1.0579  1.0021  0.4493  0.9648
 [torch.FloatTensor of size 2x4], Variable containing:
  0  1  1  0
  0  1  1  0
 [torch.FloatTensor of size 2x4])

In [961]:
nn.MultiLabelSoftMarginLoss()(x, y)

Variable containing:
 0.7789
[torch.FloatTensor of size 1]

In [962]:
x = x.data.numpy()
y = y.data.numpy()

In [963]:
x

array([[ 0.95191175, -1.7461263 ,  1.3948442 , -0.6149174 ],
       [-1.0578853 ,  1.0020678 ,  0.449279  ,  0.9647633 ]],
      dtype=float32)

In [967]:
lst = []
for k in range(len(x)):
    sm = 0
    for i in range(len(x[k])):
        sm -= y[k, i]*np.log(np.exp(x[k, i])/(1+np.exp(x[k, i]))) +\
            (1-y[k, i])*np.log(1/(1+np.exp(x[k, i])))
    lst.append(sm/len(x[k]))

lst, np.mean(lst)

([0.9597317867191937, 0.5979701125383068], 0.7788509496287502)

## MultiMarginLoss

In [1028]:
x = Variable(torch.randn(2, 4))
y = Variable(torch.LongTensor(2).random_(4))
x, y

(Variable containing:
 -1.3295  0.0457 -0.7483  0.1449
  1.6071 -0.3044 -1.7754 -1.3274
 [torch.FloatTensor of size 2x4], Variable containing:
  2
  2
 [torch.LongTensor of size 2])

In [1029]:
nn.MultiMarginLoss(margin=0.9, p=2)(x, y)

Variable containing:
 3.9957
[torch.FloatTensor of size 1]

In [1030]:
x = x.data.numpy()
y = y.data.numpy()
p=2
margin=0.9

In [1031]:
lst = []
for k in range(len(x)):
    sm = 0
    for i in range(len(x[k])):
        if i!= y[k]:
            sm += max(0, (margin - x[k, y[k]] + x[k, i])**p)
    lst.append(sm/len(x[k]))

lst, np.mean(lst)

([1.5467576592855885, 6.444682319593388], 3.9957199894394884)

## MultiLabelMarginLoss

This is a very confusing class.

Good reference here: https://blog.csdn.net/zhangxb35/article/details/72464152

### one-sample example

In [887]:
x = Variable(torch.randn(1, 4))
y = Variable(torch.LongTensor(1, 4).random_(-1, 4))
x, y

(Variable containing:
 -0.6506  0.3167 -0.6152  0.6360
 [torch.FloatTensor of size 1x4], Variable containing:
  2  1  2  3
 [torch.LongTensor of size 1x4])

In [888]:
nn.MultiLabelMarginLoss()(x, y)

Variable containing:
 0.4904
[torch.FloatTensor of size 1]

In [889]:
nn.MultiLabelMarginLoss(size_average=False)(x, y)

Variable containing:
 0.4904
[torch.FloatTensor of size 1]

In [890]:
x = x.data.numpy()
y = y.data.numpy()

In [891]:
lst = []
for k in range(len(x)):
    sm = 0
    js = []
    for j in range(len(y[k])):
        if y[k][j]<0: break 
        js.append(y[k][j])
    for i in range(len(x[k])):
        for j in js:
            if (i not in js) and (i!=j):
                print(i, j)
                sm += max(0, 1-(x[k][j] - x[k][i]))
    lst.append(sm/len(x[k]))

0 2
0 1
0 2
0 3


In [893]:
lst, np.mean(lst)

([0.49042969942092896], 0.49042969942092896)

### multi-sample example

In [884]:
x = Variable(torch.randn(3, 4))
y = Variable(torch.LongTensor(3, 4).random_(-1, 4))
x, y

(Variable containing:
  0.3417 -0.8535 -0.4887 -0.0776
 -0.2759  0.6853  0.9657 -0.7807
 -0.8177  2.2398 -0.3814  0.2490
 [torch.FloatTensor of size 3x4], Variable containing:
  2  0  3  2
  3 -1 -1  0
  1  3  3 -1
 [torch.LongTensor of size 3x4])

In [885]:
nn.MultiLabelMarginLoss()(x, y)

Variable containing:
 0.7459
[torch.FloatTensor of size 1]

In [886]:
x = x.data.numpy()
y = y.data.numpy()

lst = []
for k in range(len(x)):
    sm = 0
    js = []
    for j in range(len(y[k])):
        if y[k][j]<0: break 
        js.append(y[k][j])
    for i in range(len(x[k])):
        for j in js:
            if (i not in js) and (i!=j):
                sm += max(0, 1-(x[k][j] - x[k][i]))
    lst.append(sm/len(x[k]))

lst, np.mean(lst)

([0.3735904395580292, 1.6793406158685684, 0.1847691535949707],
 0.7459000696738561)

## TripletMarginLoss

In [1086]:
x1 = Variable(torch.randn(2, 3))
x2 = Variable(torch.randn(2, 3))
x3 = Variable(torch.randn(2, 3))
margin = 0.9
p = 2

x1

Variable containing:
 0.1787 -0.4287 -0.4904
 0.1283  1.4535  0.8618
[torch.FloatTensor of size 2x3]

In [1087]:
nn.TripletMarginLoss(margin=margin, p=p)(x1, x2, x3)

Variable containing:
 1.4847
[torch.FloatTensor of size 1]

In [1088]:
x1 = x1.data.numpy()
x2 = x2.data.numpy()
x3 = x3.data.numpy()

In [1089]:
def d(x1, x2, p):
    return sum((x1-x2)**p)**(1/p)

In [1090]:
lst = []
for k in range(len(x1)):
    sm = 0
    for i in range(len(x1[k])):
        sm += max(d(x1[k], x2[k], p)-d(x1[k], x3[k], p)+margin, 0) 
    lst.append(sm/len(x1[k]))

lst, np.mean(lst)

([1.2372308732768493, 1.7321720352507974], 1.4847014542638233)