In [1]:
import torch
torch.__version__

'1.0.0.dev20181018'

In [2]:
import numpy as np

In [3]:
bs = 8
nc = 5

In [4]:
input = torch.randn(bs, nc)
input = input.sigmoid()
input.shape

torch.Size([8, 5])

In [5]:
targs = torch.randint(high=nc, size=(bs,))
targs

tensor([4, 4, 0, 1, 1, 1, 1, 1])

In [6]:
k = 10
n = targs.shape[0]
assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

AssertionError: k (10) needs to be less than or equal to the number of classes (5)

In [7]:
k = 3
n = targs.shape[0]
assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({nc})"

In [8]:
input_rank = input.argsort(descending=True)
input_rank

tensor([[4, 1, 0, 3, 2],
        [2, 0, 3, 4, 1],
        [3, 1, 2, 4, 0],
        [3, 4, 2, 0, 1],
        [1, 0, 3, 2, 4],
        [4, 1, 3, 0, 2],
        [1, 3, 2, 4, 0],
        [2, 1, 3, 4, 0]])

In [9]:
input_rank_topk = input.argsort(descending=True)[:, :k]
input_rank_topk

tensor([[4, 1, 0],
        [2, 0, 3],
        [3, 1, 2],
        [3, 4, 2],
        [1, 0, 3],
        [4, 1, 3],
        [1, 3, 2],
        [2, 1, 3]])

In [10]:
bs = input.shape[0]
sum(t in input_rank_topk[i] for i, t in enumerate(targs))/bs

0.625

In [11]:
def accuracy_top_k(input, targs, k):
    "Compute top `k` accuracy with `targs` when `input` is bs * n_classes."
    n = targs.shape[0]
    assert 0<=k<=n , f"k ({k}) needs to be less than or equal to the number of classes ({n})"
    input_rank_topk = input.argsort(descending=True)[:, :k]
    bs = input.shape[0]
    return sum(t in input_rank_topk[i] for i, t in enumerate(targs))/bs

In [12]:
accuracy_top_k(input, targs, k)

0.625

In [13]:
from functools import partial

In [15]:
accuracy_top_3 = partial(accuracy_top_k, k=3)
accuracy_top_3(input, targs)

0.625

In [17]:
def accuracy_top_3(input, targs):
    return accuracy_top_k(input, targs, k=3)
accuracy_top_3(input, targs)

0.625