# `*` means dot product for sparse matrices

In [8]:
import numpy as np

In [9]:
a = [[1, 2,], [3, 4]]
b = [[1],[2]]

In [10]:
np.array(a)

array([[1, 2],
       [3, 4]])

In [11]:
np.array(b)

array([[1],
       [2]])

In [12]:
np.array(a) * np.array(b)

array([[1, 2],
       [6, 8]])

In [13]:
np.array(b) * np.array(a)

array([[1, 2],
       [6, 8]])

In [14]:
np.dot(np.array(a), np.array(b))

array([[ 5],
       [11]])

In [15]:
np.dot(np.array(b), np.array(a))

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [16]:
from scipy.sparse import lil_matrix

In [17]:
lil_matrix(a)

<2x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in LInked List format>

In [18]:
lil_matrix(b)

<2x1 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in LInked List format>

In [23]:
(lil_matrix(a) * lil_matrix(b)).toarray()

array([[ 5],
       [11]], dtype=int64)

In [22]:
lil_matrix(b) * lil_matrix(a)

ValueError: dimension mismatch