# Why "convolutional" in CNN's name?

In [131]:
import numpy as np
from scipy.ndimage.filters import correlate, convolve

## How does `correlate` work

### 1d

In [32]:
a = np.random.randint(5, size=10)
a

array([3, 2, 2, 0, 2, 2, 0, 2, 3, 4])

In [33]:
f = [2, 1]

In [36]:
correlate(a, f, mode='constant', cval=0.0)

array([ 3,  8,  6,  4,  2,  6,  4,  2,  7, 10])

In [38]:
for i in range(len(a)-1):
    print(a[i]*f[0] + a[i+1]*f[1])

8
6
4
2
6
4
2
7
10


### 2d

In [92]:
a = np.random.randint(10, size=36).reshape(6, -1)
a

array([[9, 8, 1, 4, 4, 6],
       [7, 8, 8, 6, 8, 3],
       [0, 9, 0, 9, 1, 2],
       [4, 6, 8, 2, 4, 0],
       [3, 2, 1, 9, 5, 5],
       [1, 3, 0, 8, 9, 9]])

In [93]:
f = np.random.randint(3, size=9).reshape(3, -1)
f

array([[2, 2, 2],
       [2, 0, 0],
       [0, 2, 0]])

In [94]:
correlate(a, f, mode='constant', cval=0.0)

array([[14, 34, 32, 14, 24, 14],
       [34, 68, 42, 52, 42, 40],
       [38, 58, 78, 48, 60, 24],
       [24, 30, 50, 54, 38, 24],
       [22, 48, 36, 46, 48, 36],
       [10, 14, 30, 30, 54, 38]])

In [95]:
for i in range(1, a.shape[0]-1):
    rslt = []
    for j in range(1, a.shape[1]-1):
        rslt.append((a[i-1:i+2, j-1:j+2] * f).sum())
    print(rslt)

[68, 42, 52, 42]
[58, 78, 48, 60]
[30, 50, 54, 38]
[48, 36, 46, 48]


## How does `convolve` work

### 1d

In [96]:
a = np.random.randint(5, size=10)
a

array([2, 4, 0, 0, 3, 4, 0, 3, 1, 0])

In [97]:
f = [2, 1]

In [98]:
convolve(a, f, mode='constant', cval=0.0)

array([10,  4,  0,  6, 11,  4,  6,  5,  1,  0])

In [99]:
rslt = []
for i in range(len(a)-1):
    rslt.append(a[i]*f[1] + a[i+1]*f[0])
print(rslt)

[10, 4, 0, 6, 11, 4, 6, 5, 1]


### 2d

In [118]:
a = np.array([[1, 2, 0, 0],
             [5, 3, 0, 4],
             [0, 0, 0, 7],
             [9, 3, 0, 0]])
a

array([[1, 2, 0, 0],
       [5, 3, 0, 4],
       [0, 0, 0, 7],
       [9, 3, 0, 0]])

In [125]:
k = np.array([[0,0,0],[1,1,0],[0,0,0]])
k

array([[0, 0, 0],
       [1, 1, 0],
       [0, 0, 0]])

In [126]:
from scipy import ndimage

ndimage.convolve(a, k, mode='constant', cval=0.0)

array([[ 3,  2,  0,  0],
       [ 8,  3,  4,  4],
       [ 0,  0,  7,  7],
       [12,  3,  0,  0]])

In [75]:
for i in range(1, a.shape[0]-1):
    rslt = []
    for j in range(1, a.shape[1]-1):
        rslt.append((a[i-1:i+2, j-1:j+2] * f).sum())
    print(rslt)

[42, 46, 41, 38]
[36, 39, 25, 40]
[44, 50, 39, 39]
[49, 45, 51, 46]


In [158]:
a = np.random.randint(10, size=36).reshape(6, -1)
a

array([[1, 3, 2, 6, 4, 2],
       [8, 0, 7, 3, 9, 1],
       [7, 1, 6, 0, 2, 7],
       [7, 2, 4, 7, 1, 8],
       [5, 6, 0, 4, 3, 6],
       [7, 7, 1, 1, 9, 3]])

In [159]:
f = np.random.randint(3, size=9).reshape(3, -1)
f

array([[2, 0, 1],
       [1, 1, 2],
       [1, 0, 0]])

In [160]:
convolve(a, f, mode='constant', cval=0.0)

array([[ 4, 29, 20, 39, 23, 19],
       [13, 44, 17, 40, 32, 21],
       [12, 43, 27, 29, 33, 12],
       [22, 31, 29, 24, 46, 13],
       [27, 29, 32, 27, 32, 21],
       [20, 22, 20, 15, 20, 21]])

In [166]:
for i in range(1, a.shape[0]-1):
    rslt = []
    for j in range(1, a.shape[1]-1):
        rslt.append(
            a[i-1, j-1] * f[2, 2] +\
            a[i-1, j] * f[2, 1] + \
            a[i-1, j+1] * f[2, 0] + \
            a[i,j-1] * f[1, 2] +\
            a[i,j] * f[1, 1] +\
            a[i,j+1] * f[1, 0] +\
            a[i+1,j-1] * f[0, 2] +\
            a[i+1,j] * f[0, 1] +\
            a[i+1, j+1] * f[0, 0]
        )
    print(rslt)

[44, 17, 40, 32]
[43, 27, 29, 33]
[31, 29, 24, 46]
[29, 32, 27, 32]


## How are correlation and convolution related

In [170]:
f_rot180 = np.rot90(f, 2)
f_rot180

array([[0, 0, 1],
       [2, 1, 1],
       [1, 0, 2]])

In [169]:
for i in range(1, a.shape[0]-1):
    rslt = []
    for j in range(1, a.shape[1]-1):
        rslt.append((a[i-1:i+2, j-1:j+2] * f_rot180).sum())
    print(rslt)

[44, 17, 40, 32]
[43, 27, 29, 33]
[31, 29, 24, 46]
[29, 32, 27, 32]


- https://youtu.be/ACU-T9L4_lI?t=1724
- http://setosa.io/ev/image-kernels/
- https://github.com/fastai/courses/blob/master/deeplearning1/nbs/convolution-intro.ipynb
- https://stackoverflow.com/questions/37969197/math-behind-scipy-ndimage-convolve