In [31]:
import numpy as np
import pandas as pd
from numpy.linalg import svd
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD

X = np.random.random((5, 8))
X.round(2)

array([[0.9 , 0.06, 0.33, 0.6 , 0.21, 0.11, 0.92, 0.76],
       [0.2 , 0.82, 0.26, 0.88, 0.92, 0.85, 0.34, 0.08],
       [0.54, 0.74, 0.11, 0.03, 0.02, 0.55, 0.72, 0.87],
       [0.68, 0.76, 0.71, 0.57, 0.45, 0.36, 0.31, 0.78],
       [0.92, 0.81, 0.34, 0.47, 0.1 , 0.4 , 0.05, 0.7 ]])

## PCA

In [46]:
k = 3

pca = PCA(n_components=k)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

## SVD

In [33]:
X.mean(0).round(2)

array([0.65, 0.64, 0.35, 0.51, 0.34, 0.45, 0.47, 0.64])

In [34]:
X_0mean = X - X.mean(0)
X_0mean.round(2)

array([[ 0.26, -0.57, -0.02,  0.09, -0.13, -0.34,  0.45,  0.12],
       [-0.45,  0.18, -0.09,  0.37,  0.58,  0.39, -0.12, -0.56],
       [-0.11,  0.1 , -0.24, -0.48, -0.32,  0.09,  0.25,  0.23],
       [ 0.03,  0.12,  0.36,  0.06,  0.11, -0.09, -0.16,  0.14],
       [ 0.27,  0.17, -0.01, -0.04, -0.24, -0.05, -0.42,  0.06]])

In [35]:
U, s, Vh = svd(X_0mean, full_matrices=False) 

## Compare SVD and PCA

### singular values

In [36]:
pca.singular_values_.round(2)

array([1.29, 0.84, 0.73])

In [37]:
s.round(2)

array([1.29, 0.84, 0.73, 0.38, 0.  ])

### componets

In [38]:
pca.components_.round(2)

array([[-0.37,  0.29,  0.02,  0.32,  0.52,  0.35, -0.28, -0.45],
       [-0.05, -0.61, -0.02,  0.38,  0.31, -0.17,  0.56, -0.21],
       [-0.44,  0.09, -0.5 , -0.44, -0.1 ,  0.35,  0.48, -0.06]])

In [39]:
Vh[:k].round(2)

array([[ 0.37, -0.29, -0.02, -0.32, -0.52, -0.35,  0.28,  0.45],
       [-0.05, -0.61, -0.02,  0.38,  0.31, -0.17,  0.56, -0.21],
       [-0.44,  0.09, -0.5 , -0.44, -0.1 ,  0.35,  0.48, -0.06]])

### transformed

In [40]:
pca.transform(X).round(2)

array([[-0.6 ,  0.62, -0.09],
       [ 1.06,  0.21,  0.15],
       [-0.4 , -0.25,  0.56],
       [ 0.05, -0.13, -0.34],
       [-0.11, -0.45, -0.27]])

In [74]:
(U[:, :k]*s[:k]).round(2)

array([[ 0.6 ,  0.62, -0.09],
       [-1.06,  0.21,  0.15],
       [ 0.4 , -0.25,  0.56],
       [-0.05, -0.13, -0.34],
       [ 0.11, -0.45, -0.27]])

In [81]:
(X_0mean@Vh[:k].T).round(2)

array([[ 0.6 ,  0.62, -0.09],
       [-1.06,  0.21,  0.15],
       [ 0.4 , -0.25,  0.56],
       [-0.05, -0.13, -0.34],
       [ 0.11, -0.45, -0.27]])

## Truncated SVD

In [51]:
svd_tr = TruncatedSVD(n_components=k)
svd_tr.fit(X_0mean)  

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=5,
       random_state=None, tol=0.0)

## Compare Truncated SVD and PCA

### singular values 
(same signs)

In [60]:
pca.singular_values_.round(2)

array([1.29, 0.84, 0.73])

In [61]:
svd_tr.singular_values_.round(2)

array([1.29, 0.84, 0.73])

### componets
(same signs)

In [64]:
pca.components_.round(2)

array([[-0.37,  0.29,  0.02,  0.32,  0.52,  0.35, -0.28, -0.45],
       [-0.05, -0.61, -0.02,  0.38,  0.31, -0.17,  0.56, -0.21],
       [-0.44,  0.09, -0.5 , -0.44, -0.1 ,  0.35,  0.48, -0.06]])

In [65]:
svd_tr.components_.round(2)

array([[-0.37,  0.29,  0.02,  0.32,  0.52,  0.35, -0.28, -0.45],
       [-0.05, -0.61, -0.02,  0.38,  0.31, -0.17,  0.56, -0.21],
       [-0.44,  0.09, -0.5 , -0.44, -0.1 ,  0.35,  0.48, -0.06]])

### transformed
(same signs)

In [68]:
pca.transform(X).round(2)

array([[-0.6 ,  0.62, -0.09],
       [ 1.06,  0.21,  0.15],
       [-0.4 , -0.25,  0.56],
       [ 0.05, -0.13, -0.34],
       [-0.11, -0.45, -0.27]])

In [69]:
svd_tr.transform(X_0mean).round(2)

array([[-0.6 ,  0.62, -0.09],
       [ 1.06,  0.21,  0.15],
       [-0.4 , -0.25,  0.56],
       [ 0.05, -0.13, -0.34],
       [-0.11, -0.45, -0.27]])